providers = ["python"]

[phases.setup]
aptPkgs = [
    "wget", 
    "gnupg", 
    "libnss3", 
    "libxss1", 
    "libasound2", 
    "libatk-bridge2.0-0", 
    "libgtk-3-0", 
    "libgbm-dev", 
    "libx11-xcb1"
]
