name: Tracking Bot

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cài Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Cài thư viện
        run: pip install -r requirements.txt

      - name: Chạy bot
        run: python bot.py
